/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/arjunrn/dumb-scaler/pkg/apis/scaler/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScalers implements ScalerInterface
type FakeScalers struct {
	Fake *FakeArjunnaikV1alpha1
	ns   string
}

var scalersResource = schema.GroupVersionResource{Group: "arjunnaik.in", Version: "v1alpha1", Resource: "scalers"}

var scalersKind = schema.GroupVersionKind{Group: "arjunnaik.in", Version: "v1alpha1", Kind: "Scaler"}

// Get takes name of the scaler, and returns the corresponding scaler object, and an error if there is any.
func (c *FakeScalers) Get(name string, options v1.GetOptions) (result *v1alpha1.Scaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scalersResource, c.ns, name), &v1alpha1.Scaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Scaler), err
}

// List takes label and field selectors, and returns the list of Scalers that match those selectors.
func (c *FakeScalers) List(opts v1.ListOptions) (result *v1alpha1.ScalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scalersResource, scalersKind, c.ns, opts), &v1alpha1.ScalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScalerList{ListMeta: obj.(*v1alpha1.ScalerList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scalers.
func (c *FakeScalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scalersResource, c.ns, opts))

}

// Create takes the representation of a scaler and creates it.  Returns the server's representation of the scaler, and an error, if there is any.
func (c *FakeScalers) Create(scaler *v1alpha1.Scaler) (result *v1alpha1.Scaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scalersResource, c.ns, scaler), &v1alpha1.Scaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Scaler), err
}

// Update takes the representation of a scaler and updates it. Returns the server's representation of the scaler, and an error, if there is any.
func (c *FakeScalers) Update(scaler *v1alpha1.Scaler) (result *v1alpha1.Scaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scalersResource, c.ns, scaler), &v1alpha1.Scaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Scaler), err
}

// Delete takes name of the scaler and deletes it. Returns an error if one occurs.
func (c *FakeScalers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scalersResource, c.ns, name), &v1alpha1.Scaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scalersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScalerList{})
	return err
}

// Patch applies the patch and returns the patched scaler.
func (c *FakeScalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Scaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scalersResource, c.ns, name, data, subresources...), &v1alpha1.Scaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Scaler), err
}
