apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scalers.arjunnaik.in
spec:
  group: arjunnaik.in
  version: v1alpha1
  names:
    kind: Scaler
    plural: scalers
  scope: Namespaced
  subresources:
      status:
        properties:
          lastScalingTimestamp:
            type: string
            format: date-time
          condition:
            type: string
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            minReplicas:
              type: integer
              minimum: 0
            maxReplicas:
              type: integer
              maximum: 100
            scaleDown:
              type: integer
              minimum: 0
              maximum: 100
            scaleUp:
              type: integer
              minimum: 0
              maximum: 100
            evaluations:
              type: integer
            scaleUpSize:
              type: integer
              minimum: 1
              maximum: 10
            scaleDownSize:
              type: integer
              minimum: 1
              maximum: 10
            target:
              properties:
                kind:
                  type: string
                name:
                  type: string
                apiVersion:
                  type: string
              required:
                - kind
                - name
                - apiVersion

