apiVersion: arjunnaik.in/v1alpha1
kind: Scaler
metadata:
  name: example-scaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleUp: 50
  scaleDown: 20
  target:
    kind: Deployment
    name: nginx
    apiVersion: apps/v1
