apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
  namespace: kube-system
  labels:
    application: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: scaler
  template:
    metadata:
      labels:
        application: scaler
    spec:
      serviceAccountName: system
      containers:
        - name: scaler
          image: arjunrn/simple-scaler:ca121dd
          args:
            - -prometheus-url=http://prometheus
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 300Mi

