/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	scalerv1alpha1 "github.com/arjunrn/dumb-scaler/pkg/apis/scaler/v1alpha1"
	versioned "github.com/arjunrn/dumb-scaler/pkg/client/clientset/versioned"
	internalinterfaces "github.com/arjunrn/dumb-scaler/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/arjunrn/dumb-scaler/pkg/client/listers/scaler/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScalerInformer provides access to a shared informer and lister for
// Scalers.
type ScalerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ScalerLister
}

type scalerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScalerInformer constructs a new informer for Scaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScalerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScalerInformer constructs a new informer for Scaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArjunnaikV1alpha1().Scalers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArjunnaikV1alpha1().Scalers(namespace).Watch(options)
			},
		},
		&scalerv1alpha1.Scaler{},
		resyncPeriod,
		indexers,
	)
}

func (f *scalerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScalerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scalerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&scalerv1alpha1.Scaler{}, f.defaultInformer)
}

func (f *scalerInformer) Lister() v1alpha1.ScalerLister {
	return v1alpha1.NewScalerLister(f.Informer().GetIndexer())
}
